spring:
  application:
    name: todo-management

  datasource:
    url: jdbc:postgresql://localhost:5455/postgres
    username: postgres
    password: 4560

  jpa:
    hibernate:
      ddl-auto: none
    # properties:
    #   hibernate:
    #     format_sql: true
    #     use_sql_comments: true
    # show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
